version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homedash
    restart: unless-stopped
    volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock"
      - ./scripts.json:/app/scripts.json
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - homedash-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - app
    networks:
      - homedash-net

networks:
  homedash-net:
    driver: bridge 