version: '3.8'

services:
  homedash:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1001}
        - DOCKER_GID=${DOCKER_GID:-999}
    container_name: homedash
    # Run the container with the host's user and group ID to avoid permission issues.
    user: "${UID:-1001}:${DOCKER_GID:-999}"
    restart: unless-stopped
    volumes:
      # Mount the Docker socket to allow the app to interact with Docker.
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount config file as read-only for security.
      - ./scripts.json:/app/scripts.json:ro
      # Mount a local data directory for persistent storage.
      - ./data:/app/data
    env_file:
      - ./.env
    ports:
      # Expose port on the host for local access/debugging.
      # Not required for Cloudflare Tunnel, which uses the internal Docker network.
      - "3000:3000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - homedash-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      - homedash
    networks:
      - homedash-net

networks:
  homedash-net:
    driver: bridge 